site_name: Simple HTML DOM documentation
site_url: https://simplehtmldom.sourceforge.io/
site_description: A simple HTML DOM parser written in PHP

repo_name: SourceForge
repo_url: https://sourceforge.net/projects/simplehtmldom/

theme:
  name: readthedocs
  custom_dir: 'custom_theme/'
  prev_next_buttons_location: both
  analytics:
    gtag: G-03SYX57C4L

markdown_extensions:
  - footnotes

extra_css: [extra.css]

nav:
  - Home: 'index.md'
  - Requirements: 'requirements.md'
  - Quick Start: 'quick-start.md'
  - FAQ:
    - Why is the parser so memory hungry?: 'faq/0001.md'
  - Manual:
    - Accessing HTML element attributes: 'manual/accessing-element-attributes.md'
    - Adding Nodes to the DOM: 'manual/adding-nodes.md'
    - Creating HTML DOM objects: 'manual/creating-dom-objects.md'
    - Customizing Parsing behavior: 'manual/customizing-parsing-behavior.md'
    - Finding HTML Elements: 'manual/finding-html-elements.md'
    - Saving DOM objects: 'manual/saving-dom-objects.md'
    - Traversing the DOM tree: 'manual/traversing-dom-tree.md'
  - Constants: 'api/constants.md'
  - HtmlDocument:
    - HtmlDocument: 'api/HtmlDocument/index.md'
    - __call: 'api/HtmlDocument/__call.md'
    - __construct: 'api/HtmlDocument/__construct.md'
    - __debugInfo: 'api/HtmlDocument/__debugInfo.md'
    - __destruct: 'api/HtmlDocument/__destruct.md'
    - __get: 'api/HtmlDocument/__get.md'
    - __toString: 'api/HtmlDocument/__toString.md'
    - childNodes: 'api/HtmlDocument/childNodes.md'
    - createElement: 'api/HtmlDocument/createElement.md'
    - createTextNode: 'api/HtmlDocument/createTextNode.md'
    - dump: 'api/HtmlDocument/dump.md'
    - expect: 'api/HtmlDocument/expect.md'
    - find: 'api/HtmlDocument/find.md'
    - firstChild: 'api/HtmlDocument/firstChild.md'
    - getElementById: 'api/HtmlDocument/getElementById.md'
    - getElementByTagName: 'api/HtmlDocument/getElementByTagName.md'
    - getElementsById: 'api/HtmlDocument/getElementsById.md'
    - getElementsByTagName: 'api/HtmlDocument/getElementsByTagName.md'
    - lastChild: 'api/HtmlDocument/lastChild.md'
    - load: 'api/HtmlDocument/load.md'
    - loadFile: 'api/HtmlDocument/loadFile.md'
    - remove_callback: 'api/HtmlDocument/remove_callback.md'
    - save: 'api/HtmlDocument/save.md'
    - set_callback: 'api/HtmlDocument/set_callback.md'
    - (protected) as_text_node: 'api/HtmlDocument/as_text_node.md'
    - (protected) copy_skip: 'api/HtmlDocument/copy_skip.md'
    - (protected) copy_until: 'api/HtmlDocument/copy_until.md'
    - (protected) copy_until_char: 'api/HtmlDocument/copy_until_char.md'
    - (protected) decode: 'api/HtmlDocument/decode.md'
    - (protected) link_nodes: 'api/HtmlDocument/link_nodes.md'
    - (protected) parse: 'api/HtmlDocument/parse.md'
    - (protected) parse_attr: 'api/HtmlDocument/parse_attr.md'
    - (protected) parse_charset: 'api/HtmlDocument/parse_charset.md'
    - (protected) prepare: 'api/HtmlDocument/prepare.md'
    - (protected) read_tag: 'api/HtmlDocument/read_tag.md'
    - (protected) remove_noise: 'api/HtmlDocument/remove_noise.md'
    - (protected) restore_noise: 'api/HtmlDocument/restore_noise.md'
    - (protected) search_noise: 'api/HtmlDocument/search_noise.md'
    - (protected) skip: 'api/HtmlDocument/skip.md'
  - HtmlNode:
    - HtmlNode: 'api/HtmlNode/index.md'
    - Definitions: 'api/HtmlNode/definitions.md'
    - __call: 'api/HtmlNode/__call.md'
    - __construct: 'api/HtmlNode/__construct.md'
    - __debugInfo: 'api/HtmlNode/__debugInfo.md'
    - __destruct: 'api/HtmlNode/__destruct.md'
    - __get: 'api/HtmlNode/__get.md'
    - __isset: 'api/HtmlNode/__isset.md'
    - __set: 'api/HtmlNode/__set.md'
    - __toString: 'api/HtmlNode/__toString.md'
    - __unset: 'api/HtmlNode/__unset.md'
    - addClass: 'api/HtmlNode/addClass.md'
    - appendChild: 'api/HtmlNode/appendChild.md'
    - childNodes: 'api/HtmlNode/childNodes.md'
    - clear: 'api/HtmlNode/clear.md'
    - convert_text: 'api/HtmlNode/convert_text.md'
    - dump: 'api/HtmlNode/dump.md'
    - dump_node: 'api/HtmlNode/dump_node.md'
    - expect: 'api/HtmlNode/expect.md'
    - find: 'api/HtmlNode/find.md'
    - find_ancestor_tag: 'api/HtmlNode/find_ancestor_tag.md'
    - firstChild: 'api/HtmlNode/firstChild.md'
    - get_display_size: 'api/HtmlNode/get_display_size.md'
    - getAllAttributes: 'api/HtmlNode/getAllAttributes.md'
    - getAttribute: 'api/HtmlNode/getAttribute.md'
    - getElementById: 'api/HtmlNode/getElementById.md'
    - getElementByTagName: 'api/HtmlNode/getElementByTagName.md'
    - getElementsById: 'api/HtmlNode/getElementsById.md'
    - getElementsByTagName: 'api/HtmlNode/getElementsByTagName.md'
    - hasAttribute: 'api/HtmlNode/hasAttribute.md'
    - hasChildNodes: 'api/HtmlNode/hasChildNodes.md'
    - hasClass: 'api/HtmlNode/hasClass.md'
    - innertext: 'api/HtmlNode/innertext.md'
    - is_utf8: 'api/HtmlNode/is_utf8.md'
    - lastChild: 'api/HtmlNode/lastChild.md'
    - makeup: 'api/HtmlNode/makeup.md'
    - nextSibling: 'api/HtmlNode/nextSibling.md'
    - nodeName: 'api/HtmlNode/nodeName.md'
    - outertext: 'api/HtmlNode/outertext.md'
    - parent: 'api/HtmlNode/parent.md'
    - parentNode: 'api/HtmlNode/parentNode.md'
    - previousSibling: 'api/HtmlNode/previousSibling.md'
    - remove: 'api/HtmlNode/remove.md'
    - removeAttribute: 'api/HtmlNode/removeAttribute.md'
    - removeChild: 'api/HtmlNode/removeChild.md'
    - removeClass: 'api/HtmlNode/removeClass.md'
    - save: 'api/HtmlNode/save.md'
    - setAttribute: 'api/HtmlNode/setAttribute.md'
    - text: 'api/HtmlNode/text.md'
    - xmltext: 'api/HtmlNode/xmltext.md'
    - (protected) is_block_element: 'api/HtmlNode/is_block_element.md'
    - (protected) match: 'api/HtmlNode/match.md'
    - (protected) parse_selector: 'api/HtmlNode/parse_selector.md'
    - (protected) seek: 'api/HtmlNode/seek.md'
  - Debug:
    - Debug: 'api/Debug/index.md'
    - disable: 'api/Debug/disable.md'
    - enable: 'api/Debug/enable.md'
    - log: 'api/Debug/log.md'
    - log_once: 'api/Debug/log_once.md'
    - setDebugHandler: 'api/Debug/setDebugHandler.md'

plugins:
  - redirects:
      redirect_maps:
        'api/HtmlDocument/load_file.md': 'api/HtmlDocument/loadFile.md'
        'api/HtmlDocument/clear.md': 'api/HtmlDocument/__destruct.md'
        'api/HtmlNode/children.md': 'api/HtmlNode/childNodes.md'
        'api/HtmlNode/first_child.md': 'api/HtmlNode/firstChild.md'
        'api/HtmlNode/has_child.md': 'api/HtmlNode/hasChildNodes.md'
        'api/HtmlNode/last_child.md': 'api/HtmlNode/lastChild.md'
        'api/HtmlNode/next_sibling.md': 'api/HtmlNode/nextSibling.md'
        'api/HtmlNode/prev_sibling.md': 'api/HtmlNode/previousSibling.md'
        'api/HtmlNode/prevSibling.md': 'api/HtmlNode/previousSibling.md'

docs_dir: 'docs'